[package]
name = "pwnedpasswords"
version = "0.1.0"
authors = ["LauH1987"]
edition = "2018"

[dependencies]
surf = "2.0.0-alpha.4"
async-std = { version = "1.6.2", features = ["attributes"] }
sha-1 = "0.9.1"